version: '3.4'

services:
  controledeveiculos:
    image: controle-veiculos
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: nork_town
      DB_USER: root
      DB_PASSWORD: nork
    links:
       - mysql
       
  mysql:
    image: mysql
    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nork
      MYSQL_DATABASE: nork_town
      MYSQL_PASSWORD: nork
    ports:
        - 3306:3306

# volumes definition here
volumes:
  # just a persistance data
  mysql-data:
    driver: local